/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.dao.AdministradorDao;
import controlador.tda.lista.ListaEnlazada;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import modelo.Administrador;

/**
 *
 * @author Usuario iTC
 */
public class FrmLogin extends javax.swing.JFrame {

    //Para Obtener la lista de personas de la base de datos
    //private ListaEnlazada<Cliente> listaClientes = new ClienteDao().listar();
    /**
     * Creates new form FrmRegistarCliente
     */
    public FrmLogin() {
        initComponents();
        this.setSize(465, 350);
        logo.setIcon(new ImageIcon("./Imagenes/Logo.png"));
        text.setVisible(false);
        passF.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        passF = new javax.swing.JPasswordField();
        text = new javax.swing.JTextField();
        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        userText = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        logo = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(500, 300));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Usuario:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(50, 140, 215, 24);

        passF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passFActionPerformed(evt);
            }
        });
        passF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                passFKeyReleased(evt);
            }
        });
        getContentPane().add(passF);
        passF.setBounds(200, 190, 220, 30);

        text.setEditable(false);
        text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textActionPerformed(evt);
            }
        });
        getContentPane().add(text);
        text.setBounds(200, 190, 220, 30);

        jCheckBox1.setText("Ver Contraseña");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox1);
        jCheckBox1.setBounds(170, 230, 120, 20);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Inicio Sesión");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(180, 100, 110, 24);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Contraseña:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(50, 190, 215, 24);
        getContentPane().add(userText);
        userText.setBounds(200, 140, 220, 30);

        jButton1.setText("Ingresar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(170, 260, 120, 30);
        getContentPane().add(logo);
        logo.setBounds(120, 20, 240, 70);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
        if (jCheckBox1.isSelected()) {
            text.setVisible(true);
            passF.setVisible(false);
        } else {
            text.setVisible(false);
            passF.setVisible(true);
        }
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            // TODO add your handling code here:
            iniciarSesion();
        } catch (Exception ex) {
            Logger.getLogger(FrmLogin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void passFKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passFKeyReleased
        // TODO add your handling code here:
        text.setText(passF.getText());
    }//GEN-LAST:event_passFKeyReleased

    private void passFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passFActionPerformed

    private void textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmLogin().setVisible(true);
            }
        });
    }

    private void iniciarSesion() throws Exception {
        ListaEnlazada <Administrador> listado = new AdministradorDao().listar();
        if (listado.buscar("Usuario", userText.getText()).getSize() == 0) {
            JOptionPane.showMessageDialog(null, "Usuario No encontrado, por favor intentelo nuevamente", "Info", JOptionPane.INFORMATION_MESSAGE);
        } else if (listado.buscar("Usuario", userText.getText()).obtenerDato(0).getPassword().equals(passF.getText())) {
            JOptionPane.showMessageDialog(null, "Sesión Iniciada Correectamente\nBienvenido!!! " + userText.getText(), "Info", JOptionPane.INFORMATION_MESSAGE);
            new FrmEditarUmbrales().setVisible(true);
            this.setVisible(false);
        } else{
            JOptionPane.showMessageDialog(null, "Contraseña no coincide, por favor intentelo nuevamente", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel logo;
    private javax.swing.JPasswordField passF;
    private javax.swing.JTextField text;
    private javax.swing.JTextField userText;
    // End of variables declaration//GEN-END:variables

}
